services:
  app:
    image: my-next-node:v1
    build:
      context: .
      dockerfile: Dockerfile.node
    depends_on:
      - db

  db:
    image: my-postgres:v1
    build:
      context: .
      dockerfile: Dockerfile.db
    environment:
      POSTGRES_USER: "appuser"
      POSTGRES_PASSWORD: "my_password"
      POSTGRES_DB: "ecsite"
    volumes:
      - postgres-for-ecsite:/var/lib/postgres/data

  test-db:
    build:
      context: .
      dockerfile: Dockerfile.db
    environment:
      POSTGRES_USER: "testuser"
      POSTGRES_PASSWORD: "my_password"
      POSTGRES_DB: "ecsite-test"
    volumes:
      - postgres-for-ecsite-test:/var/lib/postgres/data

volumes:
  postgres-for-ecsite:
  postgre-for-ecsite-test: