services:
  app:
    image: my-next-node:v1
    build:
      context: .
      dockerfile: Dockerfile.node
    tty: true
    stdin_open: true
    depends_on:
      - db

  db:
    image: my-postgres:v1
    build:
      context: .
      dockerfile: Dockerfile.db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "appuser"
      POSTGRES_PASSWORD: "my_password"
      POSTGRES_DB: "ecsite"
    volumes:
      - postgres-for-ecsite:/var/lib/postgresql

  test-db:
    build:
      context: .
      dockerfile: Dockerfile.db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: "testuser"
      POSTGRES_PASSWORD: "my_password"
      POSTGRES_DB: "ecsite-test"
    volumes:
      - postgres-for-ecsite-test:/var/lib/postgresql

volumes:
  postgres-for-ecsite:
  postgres-for-ecsite-test:
